trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'lucadr9-dockerhub-service-connection'
    repository: 'lucadr9/luca-devops-image'
    command: 'buildAndPush'
    Dockerfile: '**/dockerfile'
    tags: 'latest'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Luca Di Rienzo DevOps(59a754b8-99d8-4941-a9c1-684186c61531)'
    azureResourceGroup: 'networking-resource_group'
    kubernetesCluster: 'terraform-aks-cluster'
    manifests: 'application-manifest.yaml'